In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

In [3]:
"""
this will include more internal details about the ndarray type and more advanced array manipulations and algorithms
"""
# ndarray object internals
"""
The NumPy ndarray provides a means to interpret a block of homogeneous data
(either contiguous or strided) as a multidimensional array object. The data type, or dtype, 
determines how the data is interpreted as being floating point, integer, boolean,
or any of the other types we’ve been looking at
Part of what makes ndarray flexible is that every array object is a strided view on a
block of data. You might wonder, for example, how the array view arr[::2, ::-1]
does not copy any data. The reason is that the ndarray is more than just a chunk of
memory and a dtype; it also has “striding” information that enables the array to move
through memory with varying step sizes. More precisely, the ndarray internally consists
of the following:
"""
np.ones((10, 5)).shape
np.ones((3, 4, 5), dtype=np.float64).strides
obj = np.ones((3, 4, 5), dtype=np.float64)
obj[::-1]

'\nthis will include more internal details about the ndarray type and more advanced array manipulations and algorithms\n'

'\nThe NumPy ndarray provides a means to interpret a block of homogeneous data\n(either contiguous or strided) as a multidimensional array object. The data type, or dtype, \ndetermines how the data is interpreted as being floating point, integer, boolean,\nor any of the other types we’ve been looking at\nPart of what makes ndarray flexible is that every array object is a strided view on a\nblock of data. You might wonder, for example, how the array view arr[::2, ::-1]\ndoes not copy any data. The reason is that the ndarray is more than just a chunk of\nmemory and a dtype; it also has “striding” information that enables the array to move\nthrough memory with varying step sizes. More precisely, the ndarray internally consists\nof the following:\n'

(10, 5)

(160, 40, 8)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [5]:
# NumPy dtype Hierarchy
"""
dtypes have superclasses such as np.integer, np.floating
used in conjunction with np.issubdtype
"""
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)
# see the parent classes of a specific dtype by calling the type's mro method
np.float64.mro()
np.float32.mro()

'\ndtypes have superclasses such as np.integer, np.floating\nused in conjunction with np.issubdtype\n'

True

True

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

[numpy.float32,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 object]

In [10]:
# advanced array manipulation
# reshape arrays
arr = np.arange(8)
arr.reshape((4, 2))
arr.reshape((4, 2)).reshape((2, 4))
arr.reshape((4, 2), order='C')  # row major(default)
arr.reshape((4, 2), order='F')  # column major
# one of the passed shape dimensions can be -1, in which case the value used for that dimension will be inferred from the data
arr = np.arange(15)
arr.reshape((5, -1))
# the opposite operation of reshape is known as flattening or raveling
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()  # ravel does not produce a copy of the underlying values if the values in the result were contiguous in the original array
arr.flatten()   # the flatten method behaves like ravel except it always returns a copy of the data


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# c v.s. fortran order
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel('C')  # c(row major), traverse higher dimensions first. by default
arr.ravel('F')  # fortran(column major)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])