In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

In [3]:
"""
this will include more internal details about the ndarray type and more advanced array manipulations and algorithms
"""
# ndarray object internals
"""
The NumPy ndarray provides a means to interpret a block of homogeneous data
(either contiguous or strided) as a multidimensional array object. The data type, or dtype, 
determines how the data is interpreted as being floating point, integer, boolean,
or any of the other types we’ve been looking at
Part of what makes ndarray flexible is that every array object is a strided view on a
block of data. You might wonder, for example, how the array view arr[::2, ::-1]
does not copy any data. The reason is that the ndarray is more than just a chunk of
memory and a dtype; it also has “striding” information that enables the array to move
through memory with varying step sizes. More precisely, the ndarray internally consists
of the following:
"""
np.ones((10, 5)).shape
np.ones((3, 4, 5), dtype=np.float64).strides
obj = np.ones((3, 4, 5), dtype=np.float64)
obj[::-1]

'\nthis will include more internal details about the ndarray type and more advanced array manipulations and algorithms\n'

'\nThe NumPy ndarray provides a means to interpret a block of homogeneous data\n(either contiguous or strided) as a multidimensional array object. The data type, or dtype, \ndetermines how the data is interpreted as being floating point, integer, boolean,\nor any of the other types we’ve been looking at\nPart of what makes ndarray flexible is that every array object is a strided view on a\nblock of data. You might wonder, for example, how the array view arr[::2, ::-1]\ndoes not copy any data. The reason is that the ndarray is more than just a chunk of\nmemory and a dtype; it also has “striding” information that enables the array to move\nthrough memory with varying step sizes. More precisely, the ndarray internally consists\nof the following:\n'

(10, 5)

(160, 40, 8)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [5]:
# NumPy dtype Hierarchy
"""
dtypes have superclasses such as np.integer, np.floating
used in conjunction with np.issubdtype
"""
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)
# see the parent classes of a specific dtype by calling the type's mro method
np.float64.mro()
np.float32.mro()

'\ndtypes have superclasses such as np.integer, np.floating\nused in conjunction with np.issubdtype\n'

True

True

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

[numpy.float32,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 object]

In [10]:
# advanced array manipulation
# reshape arrays
arr = np.arange(8)
arr.reshape((4, 2))
arr.reshape((4, 2)).reshape((2, 4))
arr.reshape((4, 2), order='C')  # row major(default)
arr.reshape((4, 2), order='F')  # column major
# one of the passed shape dimensions can be -1, in which case the value used for that dimension will be inferred from the data
arr = np.arange(15)
arr.reshape((5, -1))
# the opposite operation of reshape is known as flattening or raveling
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()  # ravel does not produce a copy of the underlying values if the values in the result were contiguous in the original array
arr.flatten()   # the flatten method behaves like ravel except it always returns a copy of the data


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# c v.s. fortran order
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel('C')  # c(row major), traverse higher dimensions first. by default
arr.ravel('F')  # fortran(column major)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [4]:
# concatenating and splitting arrays
# numpy.concatenate takes a sequence(tuple, list) of arrays and joins them together in order along the input axis
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)
np.concatenate([arr1, arr2], axis=1)
# there are some convenience functions like vstack, hstack
np.vstack((arr1, arr2))
np.hstack((arr1, arr2))

# split
arr = np.random.randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3])    # 1, 3 indicate the index to split
first
second
third

# stacking helpers: r_ and c_
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

array([[ 0.69266392, -1.06910166],
       [-1.01201969, -0.34918555],
       [ 0.56241136,  0.28601688],
       [ 0.43787846,  0.20707854],
       [ 1.09999717,  0.52630799]])

array([[ 0.69266392, -1.06910166]])

array([[-1.01201969, -0.34918555],
       [ 0.56241136,  0.28601688]])

array([[0.43787846, 0.20707854],
       [1.09999717, 0.52630799]])

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.37536757,  0.04138017],
       [ 1.08092051, -0.41393749],
       [ 0.24021786, -0.26343309]])

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.37536757,  0.04138017,  3.        ],
       [ 1.08092051, -0.41393749,  4.        ],
       [ 0.24021786, -0.26343309,  5.        ]])

In [14]:
# Repeating Elements: tile and repeat
# repeat replicates each element in an array some number of times, producing a larger array
arr = np.arange(3)
arr
arr.repeat(3)
arr_2d = np.random.randn(2, 2)
arr_2d.repeat(2, axis=0)
arr_2d.repeat([2, 3], axis=0)  # pass an array of ints to repeat different number of times

# tile is a shortcut for stacking copies of an array along an axis
arr_2d
np.tile(arr_2d, 2)
np.tile(arr_2d, (1, 2))
np.tile(arr_2d, (3, 2))

array([0, 1, 2])

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

array([[ 2.45920434, -0.35309658],
       [ 2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786],
       [ 0.66994305, -1.11972786]])

array([[ 2.45920434, -0.35309658],
       [ 2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786],
       [ 0.66994305, -1.11972786],
       [ 0.66994305, -1.11972786]])

array([[ 2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786]])

array([[ 2.45920434, -0.35309658,  2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786,  0.66994305, -1.11972786]])

array([[ 2.45920434, -0.35309658,  2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786,  0.66994305, -1.11972786]])

array([[ 2.45920434, -0.35309658,  2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786,  0.66994305, -1.11972786],
       [ 2.45920434, -0.35309658,  2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786,  0.66994305, -1.11972786],
       [ 2.45920434, -0.35309658,  2.45920434, -0.35309658],
       [ 0.66994305, -1.11972786,  0.66994305, -1.11972786]])

In [17]:
# fancy indexing equivalents: take and put
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]
arr.take(inds)
arr.put(inds, 23)
arr
arr.put(inds, [40, 41, 42, 43])
arr

inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr
arr.take(inds, axis=1)

array([700, 100, 200, 600])

array([700, 100, 200, 600])

array([  0,  23,  23, 300, 400, 500,  23,  23, 800, 900])

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

array([[-2.49306423, -0.71649454, -0.03801838, -0.29262826],
       [-0.86149775, -0.54660294,  1.05782946, -0.05700488]])

array([[-0.03801838, -2.49306423, -0.03801838, -0.71649454],
       [ 1.05782946, -0.86149775,  1.05782946, -0.54660294]])