In [1]:
import numpy as np
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))
print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [9]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print(np.maximum(x, y))
print(x*5)
remainder, whole_part = np.modf(x*5)
print(remainder)
print(whole_part)
arr = np.random.randn(7) * 5
print(arr)
# Ufuncs accept an optional out argument that allows them to operate in-place on arrays
np.sqrt(arr, arr)
arr

[ 0.1010892   0.28999941  1.62428494  1.39287574 -1.29022536 -2.64644178
 -2.87358794  0.54721768]
[-0.38446493 -1.18621065  1.19984222  0.72810126 -0.09542971  0.05005931
  0.81959073 -1.25658804]
[ 0.1010892   0.28999941  1.62428494  1.39287574 -0.09542971  0.05005931
  0.81959073  0.54721768]
[  0.505446     1.44999707   8.12142472   6.96437868  -6.45112682
 -13.23220891 -14.3679397    2.73608839]
[ 0.505446    0.44999707  0.12142472  0.96437868 -0.45112682 -0.23220891
 -0.3679397   0.73608839]
[  0.   1.   8.   6.  -6. -13. -14.   2.]
[-7.84331414 -6.00863506 -1.57172243  6.85037505 -3.74419001 -0.3503937
 -1.34285366]


d:\python3.6\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in sqrt
  if sys.path[0] == '':


array([       nan,        nan,        nan, 2.61732211,        nan,
              nan,        nan])

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr = np.add(arr, arr2)
print(arr)

[ 7  9 11 13 15]


In [20]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)
print(np.sqrt(xs**2, ys**2))

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [22]:
# the numpy.where function is a vectorized version of the ternary expression: x if condition else y
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
print(result)
# the second and third arguments don't need to be arrays, can be scalars.
# A typical use of where in data analysis is to produce a new array of values based on another array
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2))     # >0->2, else ->-2
print(np.where(arr > 0, 2, arr))    # >0->2, else remains

[1.1 2.2 1.3 1.4 2.5]
[[-1.26780594 -0.27816492 -0.34784271  0.24558702]
 [ 0.26321023  0.13614334  0.29009628 -0.04444269]
 [ 1.66292745  1.09985219 -1.08916397  1.51918755]
 [-1.48046791  0.87337347 -0.4187956  -1.82918915]]
[[-2 -2 -2  2]
 [ 2  2  2 -2]
 [ 2  2 -2  2]
 [-2  2 -2 -2]]


In [24]:
# Mathematical and Statistical Methods
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean())
print(arr.sum())
print(arr.mean(axis=1))  # compute mean across the columns
print(arr.sum(axis=0))  # compute sum down the rows

[[ 0.04187699 -0.46828998 -1.37653803  0.22643065]
 [ 0.22456317  0.21186521  0.07129734 -0.4835207 ]
 [-1.37974252 -1.12437802 -1.59011759  0.46863588]
 [-0.03236291 -1.12653347  0.73301539  1.38698151]
 [ 0.02757524 -2.18559104 -0.3986631  -1.48850445]]
-0.4131000212148403
-8.262000424296806
[-0.39413009  0.00605125 -0.90640056  0.24027513 -1.01129584]
[-1.11809004 -4.6929273  -2.56100598  0.1100229 ]


In [32]:
arr = np.arange(8)
print(arr)
print(arr.cumsum())
arr2D = np.array([[0, 1, 2], [3, 5, 4], [9, 7, 8]])
print(arr2D)
print(arr2D.cumsum(axis=0))
print(arr2D.cumprod(axis=1))
print(arr.argmax())
print(arr2D.argmin(axis=1))

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]
[[0 1 2]
 [3 5 4]
 [9 7 8]]
[[ 0  1  2]
 [ 3  6  6]
 [12 13 14]]
[[  0   0   0]
 [  3  15  60]
 [  9  63 504]]
7
[0 0 1]


In [34]:
# methods for boolean arrays
arr = np.random.randn(100)
print(arr)
print((arr > 0).sum())  # number of positive number
bools = np.array([False, True, False, False])
print(bools.any())
print(bools.all())  # also work with non-boolean arrays where non-zero elements evaluate to True

[-9.17293218e-01  3.82071280e-02 -1.37153458e+00  3.47710756e-01
  2.42980027e-01 -6.78674843e-01  6.30433360e-01  1.02389870e+00
 -1.65761555e+00  3.89777376e-01 -3.44252436e-01  8.06240140e-01
 -2.52519971e-01  1.50666018e-01  1.93304271e-01  1.82601141e+00
 -2.48441669e-01  1.45320877e+00 -5.54389221e-01 -9.64147922e-02
 -3.11441079e-01 -6.32559704e-01  1.17791430e+00 -1.73885718e+00
 -1.99049998e-01  5.19625704e-01 -1.77866259e+00  2.69378913e-01
 -4.71250510e-01  1.71868772e-01 -1.34208208e+00 -1.12183244e+00
 -1.27148372e+00 -8.95889400e-01 -8.47859753e-01  9.73560324e-01
  1.04932996e+00 -1.67191735e-01 -9.23399033e-01  2.39887418e-01
  1.29613593e+00  1.24611768e-01 -6.76896768e-02 -1.05673521e+00
  8.42567149e-01  1.34805142e+00  2.65957708e-01 -8.35104198e-01
  8.47142290e-02 -4.11125776e-01  2.37368676e-01 -2.43607519e-01
 -2.84404096e-01 -7.79183338e-01  2.38972343e-01  3.71934121e-01
 -1.51800764e+00  8.37216483e-01 -1.56982525e+00 -3.95345753e-01
 -2.01823604e-01  1.18821

In [38]:
# Sorting
arr = np.random.randn(6)
print(arr)
print(arr.sort())
# the top-level method np.sort returns a sorted copy of an array instead of modifying the array in-place
# compute the quantiles of an array
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

[-2.11024248 -0.79102347 -2.13725096  1.77070927  0.14040654 -0.05380285]
None


-1.5825120769018646

In [39]:
# unique
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


In [41]:
# np.in1d tests membership of the values in one array in another, return a boolean array
values = np.array([6, 0, 0, 3, 2, 5, 6])
print(np.in1d(values, [2, 3, 6]))
print(values[np.in1d(values, [2, 3, 6])])

[ True False False  True  True False  True]
[6 3 2 6]


In [5]:
# File Input and Output with Arrays
# np.save and np.load
import numpy as np
arr = np.arange(10)
np.save('some_array', arr)
print(np.load('some_array.npy'))
# save multiple arrays in an uncompressed archive using np.savez and passing the arrays as keyword arguments
np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')  # get a dict-like object
print(arch['b'])
# If your data compresses well, you may wish to use numpy.savez_compressed instead:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
# Linear Algebra
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
print(x.dot(y))
print(np.dot(x, y))
print(x @ np.ones(3))   # @ symbol also works as an infix operator that performs matrix multiplication

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]
[[ 28.  64.]
 [ 67. 181.]]
[ 6. 15.]


In [10]:
# numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
print(inv(mat))     # inverse of the matrix
mat.dot(inv(mat))
q, r = qr(mat)
print(r)
print(np.diag(mat))
print(np.trace(mat))

[[ 1.48261312  0.67247096  0.95664578 -0.51840587  0.11192787]
 [ 0.67247096  0.72650062  0.14609186 -0.15627889 -0.27642238]
 [ 0.95664578  0.14609186  1.09819402 -0.44008956  0.38656311]
 [-0.51840587 -0.15627889 -0.44008956  0.30499421 -0.11001987]
 [ 0.11192787 -0.27642238  0.38656311 -0.11001987  0.84549687]]
[[-7.36482196  5.8734814   3.75299492 -5.06462228  0.56100173]
 [ 0.         -2.38983523 -1.34656504 -5.55598815 -1.29136506]
 [ 0.          0.         -3.99573039 -7.31109267  1.22713274]
 [ 0.          0.          0.         -1.42647651 -0.46033864]
 [ 0.          0.          0.          0.          1.0177952 ]]
[ 5.08782191  4.62308331  4.04828445 10.05259401  1.80662937]
25.61841304936228


In [12]:
"""
The numpy.random module supplements the built-in Python random with functions
for efficiently generating whole arrays of sample values from many kinds of probability
distributions.
For example, you can get a 4 × 4 array of samples from the standard
normal distribution using normal
"""
samples = np.random.normal(size=(4, 4))
print(samples)

[[-0.63321365  1.01748879  0.49437093 -0.35385508]
 [-0.63165636 -0.93472363  0.84029373 -0.42678071]
 [ 0.21721838 -0.31081044 -0.99023543  0.33320131]
 [ 0.39988678  0.94320588 -0.57045961  0.01947988]]


In [13]:
"""
you can use numpy.random.RandomState to create a random number
generator isolated from others
"""
rng = np.random.RandomState(1234)   # seed: 1234
print(rng.randn(10))

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]
